name: Publish package to the Maven Central Repositorys
on:
  release:
    types: [created]
jobs:
  publish:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: SetupMavenCentralRepository
         uses:  actions/setup-java@v3
         with:
           java-version: '11'
           distribution: 'temurin'
           server-id: repsy
           server-username: AWS_ACCESS_KEY_ID
           server-password: AWS_SECRET_ACCESS_KEY
        - name: Publish package
        run: mvn--batch-mode deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.USERNAME}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.PASSWORD}}
